# Generated by Django 5.0.6 on 2024-06-26 15:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Ism Familiya')),
                ('telefon_raqam', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Noto'g'ri formatdagi telefon raqam kiritildi! \n                      Telefon +998XXXXXXXXX shakliga to'gri kelishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('hizmat_turi', models.CharField(choices=[('GY', 'Gilam yuvish'), ('YMY', 'Yumshoq mebel yuvish'), ('B', 'Boshqa...')], default='Hizmat turini tanlang', max_length=125)),
                ('hizmat_holati', models.CharField(choices=[('Y', 'Yangi'), ('B', 'Bajarilmoqda'), ('BD', 'Bajarildi')], default='Yangi', max_length=125)),
                ('buyurtma_sanasi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buyurtma sanasi')),
                ('manzil', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
