# Generated by Django 5.0.6 on 2024-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Ism Familiya')),
                ('telefon_raqam', models.CharField(max_length=250, verbose_name='Telefon raqam')),
                ('buyurtma_sanasi', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
