# Generated by Django 5.0.6 on 2024-06-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilam_yuvish_hizmati_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='manzil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
