# Generated by Django 5.0.6 on 2024-06-26 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilam_yuvish_hizmati_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='hizmat_turi',
            field=models.CharField(choices=[('GY', 'Gilam yuvish'), ('YMY', 'Yumshoq mebel yuvish'), ('B', 'Boshqa...')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='izoh',
            field=models.TextField(default='*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='buyurtma_sanasi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buyurtma sanasi'),
        ),
    ]
