# Generated by Django 5.0.6 on 2024-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gilam_yuvish_hizmati_app', '0002_buyurtma_hizmat_turi_buyurtma_izoh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyurtma',
            old_name='izoh',
            new_name='manzil',
        ),
    ]
