# Generated by Django 5.0.6 on 2024-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilam_yuvish_hizmati_app', '0003_rename_izoh_buyurtma_manzil'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='hizmat_holati',
            field=models.CharField(choices=[('Y', 'Yangi'), ('B', 'Bajarilmoqda'), ('BD', 'Bajarildi')], default='Yangi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='hizmat_turi',
            field=models.CharField(choices=[('GY', 'Gilam yuvish'), ('YMY', 'Yumshoq mebel yuvish'), ('B', 'Boshqa...')], default='Hizmat turini tanlang'),
        ),
    ]
