# Generated by Django 5.0.6 on 2024-06-26 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilam_yuvish_hizmati_app', '0005_alter_buyurtma_telefon_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='telefon_raqam',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Noto'g'ri formatdagi telefon raqam kiritildi! \n                      Telefon +998XXXXXXXXX shakliga to'gri kelishi kerak.", regex='^\\+9989\\d{9}$|^8\\d{8}$')], verbose_name='Telefon raqam'),
        ),
    ]
